spring:
  application:
    name: greet
  config:
    import: optional:configserver:http://localhost:9093

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: refresh